language: php
sudo: false

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

install: composer update --no-interaction --no-suggest --no-progress

script:
    - ./tools/phpstan analyze --configuration=phpstan.neon.dist
    - ./tools/php-cs-fixer fix --config=.php_cs.dist --dry-run --stop-on-violation --using-cache=no
